from selenium import webdriver
driver = webdriver.Chrome()
name = input('Name : ')
last_name = input('Last Name : ')
userW = input('User : ')
pasW = input('Password : ')
print("Created by ayoub ech-chetyouy")
driver.get("https://accounts.google.com/signup/v2/webcreateaccount?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F%3Fpc%3Dtopnav-about-n-en&flowName=GlifWebSignIn&flowEntry=SignUp")
fn = driver.find_element_by_name('firstName')
fn.send_keys(name)
ln = driver.find_element_by_name('lastName')
ln.send_keys(last_name)
user = driver.find_element_by_name('Username')
user.send_keys(userW)
pas = driver.find_element_by_name('Passwd')
pas.send_keys(pasW)
Cpas = driver.find_element_by_name('ConfirmPasswd')
Cpas.send_keys(pasW)
confirm = driver.find_element_by_class_name('VfPpkd-muHVFf-bMcfAe')
confirm.click()
sui = driver.find_element_by_class_name('VfPpkd-vQzf8d')
sui.click()


